# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-30 06:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('desc', models.TextField(verbose_name='文章描述')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('image', models.ImageField(upload_to='article/%Y/%m', verbose_name='缩略图')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('view_nums', models.IntegerField(default=0, verbose_name='查看人数')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorys.Category', verbose_name='文章所属分类')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='文章标签')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article', verbose_name='所属文章')),
            ],
            options={
                'verbose_name': '文章标签',
                'verbose_name_plural': '文章标签',
            },
        ),
    ]
