# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-25 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180508_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='view_nums',
            field=models.PositiveIntegerField(default=0, verbose_name='查看人数'),
        ),
    ]
