# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-07 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.TextField(verbose_name='分类描述'),
        ),
    ]
