# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-07 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0003_auto_20180507_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='article_nums',
            field=models.IntegerField(default=0, verbose_name='文章数'),
        ),
    ]
