# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-08 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0004_category_article_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='media/default.jpg', upload_to='', verbose_name='封面图片'),
        ),
    ]
