# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-09 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0005_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='/media/default.jpg', upload_to='', verbose_name='封面图片'),
        ),
    ]
