# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-10 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0006_auto_20180509_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guestbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='昵称')),
                ('content', models.CharField(max_length=100, verbose_name='内容')),
                ('website', models.CharField(max_length=50, verbose_name='网站')),
            ],
            options={
                'verbose_name': '留言板',
                'verbose_name_plural': '留言板',
            },
        ),
    ]
