# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-10 00:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0007_guestbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbook',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
