# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-05-27 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0008_guestbook_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='网站'),
        ),
    ]
